# Generated by Django 4.0 on 2022-07-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketer',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
