# Generated by Django 4.0 on 2022-07-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_marketer_is_active_marketer_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketer',
            name='receive_money',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
