# Generated by Django 4.0.6 on 2022-07-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_marketer_receive_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_course', models.CharField(max_length=100, unique=True)),
                ('ref_user', models.CharField(max_length=100, unique=True)),
                ('money_added', models.IntegerField()),
            ],
        ),
    ]
