# Generated by Django 4.0.6 on 2022-07-07 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_ref_course_promotion_name_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='name_course',
            new_name='ref_course',
        ),
    ]
