# Generated by Django 4.0 on 2022-07-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_promotion_ref_course_alter_promotion_ref_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='money_added',
        ),
        migrations.AlterField(
            model_name='marketer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
